apiVersion: apps/v1
kind: Deployment
metadata:
  name: rpc-service-1
spec:
  selector:
    matchLabels:
      app: rpc-service-1
      version: v1
  replicas: 1
  template:
    metadata:
      labels:
        app: rpc-service-1
        version: v1
    spec:
      containers:
        - name: rpc-service
          image: "gcr.io/microservices-communication-1/rpc-service:1.0.0"
          ports:
            - containerPort: 50051
          env:
            - name: GRPC_SERVICE_ID
              value: "gRPC 1"