apiVersion: v1
kind: Service
metadata:
  name: rpc-service-1
spec:
  type: ClusterIP
  selector:
    app: rpc-service-1
    version: v1
  ports:
    - protocol: TCP
      port: 50051
      targetPort: 50051