apiVersion: v1
kind: Service
metadata:
  name: rpc-service-2
spec:
  type: ClusterIP
  selector:
    app: rpc-service-2
    version: v2
  ports:
    - protocol: TCP
      port: 50051
      targetPort: 50051