apiVersion: apps/v1
kind: Deployment
metadata:
  name: web-service-2
spec:
  selector:
    matchLabels:
      app: web-service
      version: v2
  replicas: 1
  template:
    metadata:
      labels:
        app: web-service
        version: v2
    spec:
      containers:
        - name: web-service
          image: "gcr.io/microservices-communication-1/web-service:2.0.0"
          ports:
            - containerPort: 8080