apiVersion: v1
kind: Service
metadata:
  name: web-service-2
spec:
  type: LoadBalancer
  selector:
    app: web-service-2
    version: v2
  ports:
    - protocol: TCP
      port: 60000
      targetPort: 8080